# Site settings
title: "Aeri resume"
description: "2020 소프트웨어혁명 위클리코딩"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Aeri"
resume_title:                   "2020 SW revolution weekly coding"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "ael_00@kookmin.ac.kr"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "01093834051"
resume_contact_address:         "서울시 성북구 정릉동"

resume_header_contact_info:     "서울시 성북구 정릉동, Springfield • 01093834051 • ael_00@kookmin.ac.kr"
display_header_contact_info:    "false"

resume_header_intro: "<p>모빌리티, 딥러닝과 임베디드에 관심 많은 학부생입니다! 2021년 관련 대학원에 진학예정입니다.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "no"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/Aibia"
  # resume_twitter_url:           "http://twitter.com/jglovier"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/%EC%95%A0%EB%A6%AC-%EC%A0%95-a4447716b/"
  # resume_instagram_url:         "insert your Instagram URL here"
  # resume_website_url:           "http://joelglovier.com"
  # resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
